### ISSUE TITLE
Provide callback on message sent

### ISSUE THREAD

**Issue by atombender** [phuesler/ain#29]
We're having an issue where our app (a web worker) catches exceptions and logs a syslog message right before it exits. Unfortunately, we have to do this:

```javascript
    logger.error("some message");
    setTimeout(function() { process.exit(1); }, 500);
```

The reason is that if we exit right away, the logger probably hasn't finished sending. The timeout is arbitrary and probably isn't dependable (zero isn't sufficient) if the load is high.

A solution would be to let `send()` accept a callback. Thoughts?

**Comment by phuesler** [comment]
[Send ](http://nodejs.org/api/dgram.html#dgram_socket_send_buf_offset_length_port_address_callback) does provide a callback, so technically, this is possible. Since it is UDP, there is not guarantee, that the datagram has actually been received.

**Comment by atombender** [comment]
Of course. But the callback would let us exit once the underlying `send` socket call has finished, which is sufficient.

**Comment by phuesler** [comment]
I'll look into it. Given the current code base, this is an extensive change but as fare as I can tell, it will not break the API for existing users.

**Comment by phuesler** [comment]
Since ain allows simple format arguments in the form of a variable argument list, I don't know how to add support for a callback without breaking the current API. I will give it some more thought.

````javascript
logger.notice("my object encoded as a String %s", myobject);
`````

**Comment by phuesler** [comment]
I pushed the first draft to support callbacks https://github.com/phuesler/ain/tree/send_with_callback

**Comment by atombender** [comment]
Looks great. Breaking the current API should be fine, though, if you increment the major version.

**Comment by phuesler** [comment]
I'm more concerned about making the API and code more complicated than it needs to be and less with SEMVER semantics. The draft mentioned above keeps the same external API but jumps through a few hoops internally to do so. Maybe the printf semantic is just nice to have and could be removed from ain altogether

**Comment by atombender** [comment]
I think your changes make sense. Having built-in formatting is pretty important in a logger.

**Comment by phuesler** [comment]
I have pushed version 1.5 to npm

**Comment by atombender** [comment]
Awesome. Thanks!
