### ISSUE TITLE
Fails to install using io.js

### ISSUE THREAD

**Issue by phuesler** [phuesler/ain#30]
There is a problem with unix-dgram

**Comment by mderazon** [comment]
iojs/io.js#456

**Comment by mderazon** [comment]
try to update to `v0.1.2`, I think it's solved

**Comment by phuesler** [comment]
Thank you for the info. I'll check.

**Comment by badunk** [comment]
Should be fixed with https://github.com/phuesler/ain/commit/e4e6a861a9f1664cefbf84bd6cffd892b3ae5d59

**Comment by phuesler** [comment]
thanks for taking care of this, Duncan! :bow:

**Comment by badunk** [comment]
:+1:
