### ISSUE TITLE
Broken in 0.12 with cluster

### ISSUE THREAD

**Issue by seangarner** [phuesler/ain#33]
When ain2 is used in an application with cluster on node 0.12 it throws this exception.

```
assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at SharedHandle.add (cluster.js:97:3)
    at queryServer (cluster.js:480:12)
    at Worker.onmessage (cluster.js:438:7)
    at ChildProcess.<anonymous> (cluster.js:692:8)
    at ChildProcess.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
```

I originally thought it was a recluster problem (doxout/recluster#23) but in the end tracked it down to this line in ain2:
```js
        // HACK: On Node v0.11.x bind the socket to ensure that it works when clustering
        // THis should be a temporary fix until node fixes the cluster module
        if (/^v0\.11\..*$/.test(process.version)) {
```

If I edit that and set it to 0.12 then it stops throwing the exception, but a PR with a new regex seems short sighted given the comment.

**Comment by phuesler** [comment]
I went ahead and patched it anyway. Can you give this a try?

https://github.com/phuesler/ain/tree/socket_bind_patch_node_v12

I looked at [the assertion in cluster.js](https://github.com/joyent/node/blob/master/lib/cluster.js#L97) and it seems that the worker it tries to add is still in the list of workers.

````javascript
SharedHandle.prototype.add = function(worker, send) {
  assert(this.workers.indexOf(worker) === -1);
  this.workers.push(worker);
  send(this.errno, null, this.handle);
};
````

At this point, I have no idea, why these 2 things are related.

**Comment by seangarner** [comment]
I dropped a comment in that commit.  It doesn't work for me unless I use the modification I provided.  When I do use the modification the bug is fixed for me in node 0.12.0.

**Comment by phuesler** [comment]
* I made a mistake in the regular expression. Does this fix the problem for you?
* I have noticed a problem with the test suite when I do this for unix_dgram sockets. Are you using udp4 or unix_dgram?

**Comment by seangarner** [comment]
@phuesler yea, that's worked.  I'm using udp4.

**Comment by phuesler** [comment]
realeased patch version v1.5.2 https://www.npmjs.com/package/ain2

**Comment by seangarner** [comment]
fantastic, thankyou kindly :)
